### ISSUE TITLE
Issue: "Please connect to a live streaming service above", but there's nothing above

### ISSUE THREAD

**Issue by TheAlexPlus** [FaeyUmbrea/ethereal-plane#3]
Heyo, it's me again!

I log in to Patreon and it doesn't give me any options like in the examples in the wiki.

I WAS able to get it to work on my local install on my computer without issue and so I figured it was a result of not being fully updated to Foundry V10.312 on my hosted server, but I updated today and I'm having the same problem.

Not sure if it's related, but my console is constantly updating with the same error:

"websocket.js:54 WebSocket connection to 'ws://ep.void.monster/socket.io/?EIO=4&transport=websocket&sid=sLwC1lIh-8sjWeFrAAjw' failed: Invalid frame header
patreon.js:185 Refreshed Tokens
patreon.js:57 Ethereal Plane | Connecting to Patreon Server
patreon.js:69 Ethereal Plane | Api Version OK
patreon.js:179 Ethereal Plane | Token Expired - Refreshing
patreon.js:182 refreshing with fUvu5rqYiNcFUfOQqdlpH1cWrU0aued3z2BnSuhqsvIXW1DZqo6fZhpd4U6oCGJ3jdcr5RsBuSvdE-OwrjwQDvxsQexPPcQ0gjKyT0hdpu-CkEBqzATIxQg5jznmeGET"

**Comment by FaeyUmbrea** [comment]
Hi there, you might run into an issue related to the login system.
Try logging out and back in again

**Comment by TheAlexPlus** [comment]
Thank you for the quick response!
Unfortunately, I've tried logging out and nothing seems to happen.  It doesn't ever really register that Ive clicked it.
Sometimes after reloading a few times, it shows that I'm logged out, but after logging back in and trying this process multiple times, I've never gotten it to work on my hosted server.

Is it possible this is related to node?  that might be the only thing that's not updated.

**Comment by FaeyUmbrea** [comment]
Are you running your local and your hosted server at the same time using the same Patreon account?

**Comment by FaeyUmbrea** [comment]
Oh wait, is your local install on foundry 11?

**Comment by TheAlexPlus** [comment]
I'm not trying to.  Not at the same time, at least.
In testing this out, I've been trying to make sure to quit out of one before testing the other, but there probably was a moment at the beginning where they overlapped.
I realize there might be a conflict if they were both active at once, but even in times where they definitely weren't, I've never been able get the hosted server to work and ive always had the issue with not being able to properly log out.

No both servers are running 10.312 at this point.
The online server used to be on like 10.302 or something, but i updated it in trying to fix this but it didn't have an effect

**Comment by TheAlexPlus** [comment]
When i try to log out i get this error in the console:
patreon.js:264 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'disconnect')
    at bn.disconnect (patreon.js:264:17)
    at bn.logout (patreon.js:357:10)
    at Object.fn (patreon.js:31:58)
    at #call (foundry.js:724:20)
    at Hooks.call (foundry.js:706:38)
    at HTMLButtonElement.xl (PatreonConfig.svelte:19:11)

**Comment by FaeyUmbrea** [comment]
Hm this is very odd. The error you are getting is due to socket.io not being able to establish a connection properly. 
This process is done entirely in the browser.

The odd part is that part of it works fine, because I use the same connection to do the token refreshing.

Can you make a completely new world on the hosted server and see if the issue still occurs there or if its specific to that one world?

**Comment by TheAlexPlus** [comment]
can do.  i will report back

**Comment by TheAlexPlus** [comment]
When I create a fresh world, it remembers the settings from the other world.  This was true on my local server too, but i didn't have a problem logging out there.
But alas, i still cannot log out from patreon or disconnect from twitch

**Comment by FaeyUmbrea** [comment]
Okay, let's see if there is issues with the data kept in local storage. 

Please first turn off the module by unchecking the enable setting in module settings.

Then, please run the following two lines in your browser console:

`game.settings.set("ethereal-plane","refresh-token","")`
`game.settings.set("ethereal-plane","authentication-token","")`

after that, try logging back in with your patreon account

**Comment by TheAlexPlus** [comment]
Ok so...  Even with the module not enabled via the check box in it's settings, im getting those repeated error messages in the console.
as soon as I entered the first line. "game.settings.set("ethereal-plane","refresh-token","")"  it stopped.
I entered the second one and reloaded.
When it came back up, it looked to have been successfully logged out.
I clicked to log into patreon.
It prompted me as usual and i clicked allow.
Then, it said I was logged in, but it hadn't cleared my twitch log in.. so it said that i was already logged into twitch.. aka: it only showed me the disconnect option.
When I click disconnect I get this error:
TypeError: Error thrown in hooked function '' for hook 'ethereal-plane.twitch-disconnect'. Cannot read properties of undefined (reading 'emit')
    at bn.twitchDisconnect (patreon.js:318:17)
    at Object.fn (patreon.js:36:12)
    at #call (foundry.js:724:20)
    at Hooks.call (foundry.js:706:38)
    at HTMLButtonElement.Wl (PatreonConfig.svelte:27:11)
    
    And when I click on Log out, I get this error:
    Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'disconnect')
    at bn.disconnect (patreon.js:264:17)
    at bn.logout (patreon.js:357:10)
    at Object.fn (patreon.js:31:58)
    at #call (foundry.js:724:20)
    at Hooks.call (foundry.js:706:38)
    at HTMLButtonElement.xl (PatreonConfig.svelte:19:11)

**Comment by FaeyUmbrea** [comment]
Alright, I've downloaded a clean V10 linux bundle from the foundry website and installed the module into it in the current release (1.4.0)

I can not reproduce the issue you are presently running into on my end. The test also showed that the issue is not actually that any old parameters are stuck. 

It might either be a problem with the browser you are using or some old files of your foundry installation or an outdated module version sticking around on either the server or your browser cache.

**Comment by TheAlexPlus** [comment]
So, I switched to Firefox instead of Chrome and I'm having the same issue.
Which is mainly that I can log in to patreon but it doesn't show me the option to log in to twitch.

I know i was having issues "logging out of twitch" but technically i had never really officially logged in.. i had copied settings from the working foundry instance.   
I was able to clear that and start fresh, but the settings never load a twitch log in button.

The repeating error message is different in firefox too:
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://ep.void.monster/socket.io/?EIO=4&transport=polling&t=OkxGnuS. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 301.
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://ep.void.monster/socket.io/?EIO=4&transport=polling&t=OkxGnuS. (Reason: CORS request did not succeed). Status code: (null).

When I click to log out, I get this error:
Uncaught (in promise) TypeError: this.socket is undefined
    disconnect patreon.js:264
    logout patreon.js:357
    bn patreon.js:31
    #call foundry.js:724
    call foundry.js:706
    xl PatreonConfig.svelte:19
    q dom.js:361
    m PatreonConfig.svelte:67
    m PatreonConfig.svelte:62
    K Component.js:44
    m ConfigUI.svelte:70
    m CollapsibleSection.svelte:17
    m CollapsibleSection.svelte:13
    K Component.js:44
    m ConfigUI.svelte:69
    m ConfigUI.svelte:87
    m ApplicationShell.svelte:408
    m ApplicationShell.svelte:360
    K Component.js:44
    m ConfigUI.svelte:25
    K Component.js:44
    he Component.js:162
    ea ConfigUI.svelte:25
    Oi loadSvelteConfig.js:91
    _injectHTML SvelteApplication.js:507
    _render foundry.js:5131
    _render SvelteApplication.js:886
    render foundry.js:5067
    showSettings settings.js:265
    bo settings.js:258
    _onClickSubmenu foundry.js:72002
    jQuery 9
    activateListeners foundry.js:71987
    _render foundry.js:5138
    _render foundry.js:5822
    _render foundry.js:59979
    render foundry.js:5067
    _onSettingsButton foundry.js:76757
    jQuery 9
    activateListeners foundry.js:76741
    _render foundry.js:5138
    _render foundry.js:60402
    _render foundry.js:60172
    render foundry.js:5067
    initializeUI foundry.js:8069
    setupGame foundry.js:7931
    _initializeGameView foundry.js:8999
    _initializeView foundry.js:8975
    initialize foundry.js:7825
    async* foundry.js:79752
    async* foundry.js:79734

**Comment by FaeyUmbrea** [comment]
Yeah, the twitch login button only appears when the actual post-authentication connection succeeds. But for what ever reason it is not working on your hosted foundry instance. 

SInce it's reocurring cross browser the only good explanation is outdated or corrupted files sticking around.

You should try and replace them one by one. 
Step 1:

In dev-tools for your hosted instance, go to storage and clear site data. 

Step 2: 

If that doesn't work, delete the module and redownload the latest version

Step 3: 

If that doesn't work, delete the foundry installation on your server (make sure you don't accidentally delete your Data though) and reinstall it from a clean download.

**Comment by TheAlexPlus** [comment]
I started a completely new server and installed everything fresh and the exact same issue occurs.

I think there's something about the module that doesn't jive with a hosted Foundry instance.

You were able to test that it works on a local install, which had always worked on my end.  So idk.. it seems related to that somehow.

**Comment by FaeyUmbrea** [comment]
I have a working hosted instance too, so that's not it

**Comment by FaeyUmbrea** [comment]
How exactly are you hosting your foundry instance?

**Comment by TheAlexPlus** [comment]
it's installed on an amazon ec2 instance

**Comment by FaeyUmbrea** [comment]
One thing that strikes me as odd is that your error code has the protocol for the websocket connection as "ws://" instead of "wss://" which it should be.

Does your foundry installation have a valid HTTPS certificate?

**Comment by TheAlexPlus** [comment]
if that requires the SSL stuff to be set up, it does not.
When i load the server it says not secure in the address bar

**Comment by FaeyUmbrea** [comment]
Ahhhh there's the issue then!

Most modern browsers have something called mixed content protection. This blocks an http site from loading https content and vice versa. The EtherealPlane API only accepts connections via HTTPS for security reasons.

This means that your browser does not allow your foundry instance to establish a connection because the protocol does not match.

The reason this does not cause an issue on your local installation is because mixed content protection is not active on localhost for development purposes. 

You can get a free SSL certificate for your foundry instance from lets-encrypt. After you set that up, it should work

**Comment by TheAlexPlus** [comment]
aaah.  ok that's incredible! thank you so much for spending the time with me!
that sounds super promising but I'll be back to let you know either way!

**Comment by FaeyUmbrea** [comment]
As a last resort, if you pay for your foundry server anyway, you might want to consider one of the official hosting providers. A lot of other users of EP use Forge, so thats worth checking out. I selfhost personally, so I can't give a direct recommendation for lack of experience.

**Comment by FaeyUmbrea** [comment]
More good news! I was able to reproduce the issue by testing on a foundry installation without SSL, so that's definitely the problem here. If you need any help setting up SSL for your specific hosting situation I recommend checking out the official Foundry Discord. They have a setup help channel over there.
